name: Release to production
on:
  push:    
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "generated artifacts"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false